# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            A Blog
tagline:          'Hao Fu'
description:      Purely for the purpose of using GitHub to write blogs. By Hao Fu.
url:              http://solosodium.github.io
baseurl:          /

author:
  name:           'Hao Fu'
  url:            https://twitter.com/solosodium

paginate:         5

# Custom vars
version:          2.1.0

github:           
  repo:           https://github.com/solosodium
